steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install', '-DskipTests']
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/$APP_NAME:latest'
  - '--tag=gcr.io/$PROJECT_ID/$APP_NAME:$COMMIT_SHA'
  - '--tag=gcr.io/$PROJECT_ID/$APP_NAME:$BUILD_ID'
  - '.'
  id: 'build-image-spring-boot-app'

# - name: 'gcr.io/cloud-builders/kubectl'
#   args:
#   - 'set'
#   - 'image'
#   - 'deployment/${DEPLOYMENT_NAME}'
#   - '${CONTAINER_NAME}=gcr.io/${$PROJECT_ID}/${CONTAINER_NAME}:${$COMMIT_SHA}'
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=${ZONE}'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=${GKE_CLUSTER}'

substitutions:
  APP_NAME: simple-spring-boot-app
  CONTAINER_NAME: simple-spring-boot-container
  DEPLOYMENT_NAME: simple-spring-boot-deployment
  ZONE: us-central1-a
  GKE_CLUSTER: simple-spring-boot-k8s-cluster

options:
    substitution_option: 'ALLOW_LOOSE'

images:
- 'gcr.io/$PROJECT_ID/simple-spring-boot-app:latest'
- 'gcr.io/$PROJECT_ID/simple-spring-boot-app:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/simple-spring-boot-app:$BUILD_ID'