steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install', '-DskipTests']
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/$_APP_NAME:latest'
  - '--tag=gcr.io/$PROJECT_ID/$_APP_NAME:$COMMIT_SHA'
  - '--tag=gcr.io/$PROJECT_ID/$_APP_NAME:$BUILD_ID'
  - '.'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENT_NAME}'
  - '${_CONTAINER_NAME}=gcr.io/$PROJECT_ID/${_CONTAINER_NAME}:$COMMIT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

substitutions:
  _APP_NAME: simple-spring-boot-app
  _CONTAINER_NAME: simple-spring-boot-container
  _DEPLOYMENT_NAME: simple-spring-boot-app
  _ZONE: us-central1-a
  _GKE_CLUSTER: simple-spring-boot-cluster

options:
    substitution_option: 'ALLOW_LOOSE'

images:
- 'gcr.io/$PROJECT_ID/simple-spring-boot-app:latest'
- 'gcr.io/$PROJECT_ID/simple-spring-boot-app:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/simple-spring-boot-app:$BUILD_ID'