steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install', '-DskipTests']
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/simple-spring-boot:latest'
  - '--tag=gcr.io/$PROJECT_ID/simple-spring-boot:$COMMIT_SHA'
  - '--tag=gcr.io/$PROJECT_ID/simple-spring-boot:$BUILD_ID'
  - '.'
  id: 'build-image-spring-boot-app'
images:
- 'gcr.io/$PROJECT_ID/simple-spring-boot:latest'
- 'gcr.io/$PROJECT_ID/simple-spring-boot:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/simple-spring-boot:$BUILD_ID'