apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: simple-spring-boot-container
        image: gcr.io/eminent-maker-293204/simple-spring-boot-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: simple-spring-boot-service
spec:
  selector:
    app: spring-boot-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 60000
      targetPort: 8080
      # port for the external IP address
      # 30000 - 32767
      # nodePort: 31000

